---
title: "R Notebook"
output: html_notebook
---

Q1:

```{r}
library(tidyverse)
library(janitor)
phones <- read_csv("data/20190928-items.csv") %>%
  clean_names()
```
Q2:

```{r}
phones %>% 
  group_by(brand) %>% 
  summarise(total_brand = n()) %>% 
  arrange(-total_brand) %>% 
  slice_max(total_brand)
```
q3:

```{r}
phones_stats <- phones %>% 
  filter(brand == "Samsung") %>% 
  summarise(mean = mean(rating),
            sd = sd(rating))

phones %>% 
  ggplot(aes(x = rating)) +
  geom_histogram(aes(y = ..density..), colour = "gold", size = 1.5) +
  stat_function(
    fun = dnorm,
    args = list(
      mean = phones_stats$mean,
      sd = phones_stats$sd
    ),
    col = "black",
    size = 1.5
  )
```

The normal distribution seems to give a good model of the ratings.

Q4:

```{r}
phones %>% 
  mutate(z_rating = scale(rating)) %>% 
  mutate(within_one = if_else(abs(z_rating) <= 1, TRUE, FALSE),
    within_two = if_else(abs(z_rating) <= 2, TRUE, FALSE),
    within_three = if_else(abs(z_rating) <= 3, TRUE, FALSE)) %>% 
  summarise(
    nwithin_one = sum(within_one) / n(),
    nwithin_two = sum(within_two) / n(),
    nwithin_three = sum(within_three) / n()
  )
```


```{r}
phones %>% 
  filter(brand == "Samsung") %>% 
  qqnorm()

