---
title: "R Notebook"
output: html_notebook
---

Q1:

```{r}
weather_forecast <- list("thursday" = 
                           list("temp" = "14 degrees",
                                "rain" = '80%',
                                "wind" = "10mph"),
                         "friday" = 
                           list("temp" = "11 degrees",
                                "rain" = '40%',
                                "wind" = "12mph"),
                         "saturday" = 
                           list("temp" = "12 degrees",
                                "rain" = '70%',
                                "wind" = "14mph"))
```

Q2i:

```{r}
weather_forecast$thursday$rain
```

ii:

```{r}
weather_forecast$friday$wind
```

iii:

```{r}
weather_forecast[[1]][[1]]
```

Q3:

```{r}
temperatures <- matrix(c(13, 10, 11, 12, 10, 12, 10, 9, 13, 14, 14,
                       11, 9, 9), byrow = TRUE, nrow = 2, ncol = 7)


```

Q4i:

```{r}
temperatures[2, 3]
```

Q4ii:

```{r}
temperatures[2, ]
```

Q4iii:
```{r}
temperatures[ ,c(1, 3, 5)]
```


Q5:

```{r}
pre_append <- function(x){
  if (is.character(x)){
    return(stringr::str_c("The answer is ", x))
  }
  if (is.numeric(x)){
    if (x < 10){
      return(x)
    } else{
      return(x / 10)
    }
  }
  return("Invalid input")
}


pre_append(TRUE)
```


Q6:
```{r}
x <- c("a", "b", "c")
y <- c("a", "d", "c")
all(x == y)


same_check <- function(x, y){
  if (all(x ==y)){
    return("Everything the same")
  }
  sorted_x <- sort(x)
  sorted_y <- sort(y)
  if(all(sorted_x == sorted_y)){
    return("The same")
  }
  return("Different")
}

same_check(x, y)
```

Q7:

```{r}
twelve_matrix <- matrix(nrow = 12, ncol =  12)

for (i in 1:12){
  for (j in 1:12){
    twelve_matrix[i, j] <- i*j
  }
}
twelve_matrix
```


q8:

```{r}
library(stringr)
counts <- matrix(nrow = 9, ncol = 1)
numbers <- sample(1:5, size = 50, replace = TRUE) 
art <- function(x){
  for (m in 1:9){
    counts[m] <- sum(str_count(x, pattern = as.character(m)))
  }
  for (num in counts) {
    for (rep in 1:num){
      if(num == 0){
        break
      }
      cat("*")
    }
    if (num != 0)
      cat("\n")
  }
}

art(numbers)

```



